
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DEF NULL HASHMAP SORTEDMAP MAP VECTOR CONJUNTO STR LOOP WHILE DO WHEN PRINTLN RECUR DEFN METODOFIRST LISTA METODONTH IF DOSEQ TRUE FALSE READLINE NOT AND OR ENTERO FLOTANTE CHAR STRING PAR_DER PAR_IZQ COR_DER COR_IZQ SUM REST PRODUCT DIVISION EQUAL NOT_EQUAL GREATER_THAN LESS_THAN GREATER_THAN_EQUAL LESS_THAN_EQUAL COM_SIM NOMBRE HASH LLAV_IZQ LLAV_DERalgoritmo : variable\n                 | expresion\n    variable : PAR_IZQ DEF NOMBRE expresion PAR_DERexpresion : valor\n                 | estructura\n    estructura : PAR_IZQ LISTA PAR_IZQ valor PAR_DER PAR_DER\n                  | COM_SIM PAR_IZQ valor PAR_DER\n    estructura : PAR_IZQ CONJUNTO COM_SIM PAR_IZQ valor PAR_DER PAR_DER\n                  | HASH LLAV_IZQ valor LLAV_DER\n    estructura : PAR_IZQ VECTOR valor PAR_DER\n                  | COR_IZQ valor COR_DER\n    estructura : LLAV_IZQ STRING STRING LLAV_DER\n                  | PAR_IZQ mapas STRING STRING PAR_DER\n    mapas : SORTEDMAP REST MAP\n             | HASHMAP REST MAP\n    compuesto : valor\n                 | compuesto\n    valor : numero\n             | NOMBRE\n             | booleano\n             | cadena\n    cadena : STRING\n              | PAR_IZQ STR STRING STRING PAR_DER\n    booleano : TRUE\n                | FALSE\n    numero : ENTERO\n              | FLOTANTE\n    '
    
_lr_action_items = {'PAR_IZQ':([0,11,14,21,23,28,29,33,34,35,48,],[4,28,32,34,32,32,32,45,32,48,32,]),'NOMBRE':([0,14,20,23,28,29,33,34,48,],[5,5,33,5,5,5,5,5,5,]),'COM_SIM':([0,22,33,],[11,35,11,]),'HASH':([0,33,],[12,12,]),'COR_IZQ':([0,33,],[14,14,]),'LLAV_IZQ':([0,12,33,],[13,29,13,]),'ENTERO':([0,14,23,28,29,33,34,48,],[16,16,16,16,16,16,16,16,]),'FLOTANTE':([0,14,23,28,29,33,34,48,],[17,17,17,17,17,17,17,17,]),'TRUE':([0,14,23,28,29,33,34,48,],[18,18,18,18,18,18,18,18,]),'FALSE':([0,14,23,28,29,33,34,48,],[19,19,19,19,19,19,19,19,]),'STRING':([0,13,14,23,24,25,28,29,30,33,34,37,38,48,52,53,],[15,30,15,15,37,38,15,15,43,15,15,50,51,15,-14,-15,]),'$end':([1,2,3,5,6,7,8,9,10,15,16,17,18,19,44,49,54,55,56,57,60,61,62,64,],[0,-1,-2,-19,-4,-5,-18,-20,-21,-22,-26,-27,-24,-25,-11,-10,-7,-9,-12,-3,-13,-23,-6,-8,]),'DEF':([4,],[20,]),'LISTA':([4,45,],[21,21,]),'CONJUNTO':([4,45,],[22,22,]),'VECTOR':([4,45,],[23,23,]),'STR':([4,32,45,],[25,25,25,]),'SORTEDMAP':([4,45,],[26,26,]),'HASHMAP':([4,45,],[27,27,]),'COR_DER':([5,8,9,10,15,16,17,18,19,31,61,],[-19,-18,-20,-21,-22,-26,-27,-24,-25,44,-23,]),'PAR_DER':([5,6,7,8,9,10,15,16,17,18,19,36,41,44,46,47,49,50,51,54,55,56,58,59,60,61,62,63,64,],[-19,-4,-5,-18,-20,-21,-22,-26,-27,-24,-25,49,54,-11,57,58,-10,60,61,-7,-9,-12,62,63,-13,-23,-6,64,-8,]),'LLAV_DER':([5,8,9,10,15,16,17,18,19,42,43,61,],[-19,-18,-20,-21,-22,-26,-27,-24,-25,55,56,-23,]),'REST':([26,27,],[39,40,]),'MAP':([39,40,],[52,53,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'algoritmo':([0,],[1,]),'variable':([0,],[2,]),'expresion':([0,33,],[3,46,]),'valor':([0,14,23,28,29,33,34,48,],[6,31,36,41,42,6,47,59,]),'estructura':([0,33,],[7,7,]),'numero':([0,14,23,28,29,33,34,48,],[8,8,8,8,8,8,8,8,]),'booleano':([0,14,23,28,29,33,34,48,],[9,9,9,9,9,9,9,9,]),'cadena':([0,14,23,28,29,33,34,48,],[10,10,10,10,10,10,10,10,]),'mapas':([4,45,],[24,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> algoritmo","S'",1,None,None,None),
  ('algoritmo -> variable','algoritmo',1,'p_algoritmo','implementation_nico.py',9),
  ('algoritmo -> expresion','algoritmo',1,'p_algoritmo','implementation_nico.py',10),
  ('variable -> PAR_IZQ DEF NOMBRE expresion PAR_DER','variable',5,'p_variable','implementation_nico.py',14),
  ('expresion -> valor','expresion',1,'p_expresion','implementation_nico.py',17),
  ('expresion -> estructura','expresion',1,'p_expresion','implementation_nico.py',18),
  ('estructura -> PAR_IZQ LISTA PAR_IZQ valor PAR_DER PAR_DER','estructura',6,'p_estructura_lista','implementation_nico.py',22),
  ('estructura -> COM_SIM PAR_IZQ valor PAR_DER','estructura',4,'p_estructura_lista','implementation_nico.py',23),
  ('estructura -> PAR_IZQ CONJUNTO COM_SIM PAR_IZQ valor PAR_DER PAR_DER','estructura',7,'p_estructura_conjunto','implementation_nico.py',27),
  ('estructura -> HASH LLAV_IZQ valor LLAV_DER','estructura',4,'p_estructura_conjunto','implementation_nico.py',28),
  ('estructura -> PAR_IZQ VECTOR valor PAR_DER','estructura',4,'p_estructura_vector','implementation_nico.py',32),
  ('estructura -> COR_IZQ valor COR_DER','estructura',3,'p_estructura_vector','implementation_nico.py',33),
  ('estructura -> LLAV_IZQ STRING STRING LLAV_DER','estructura',4,'p_estructura_mapa','implementation_nico.py',37),
  ('estructura -> PAR_IZQ mapas STRING STRING PAR_DER','estructura',5,'p_estructura_mapa','implementation_nico.py',38),
  ('mapas -> SORTEDMAP REST MAP','mapas',3,'p_mapas','implementation_nico.py',42),
  ('mapas -> HASHMAP REST MAP','mapas',3,'p_mapas','implementation_nico.py',43),
  ('compuesto -> valor','compuesto',1,'p_compuesto','implementation_nico.py',47),
  ('compuesto -> compuesto','compuesto',1,'p_compuesto','implementation_nico.py',48),
  ('valor -> numero','valor',1,'p_valor','implementation_nico.py',52),
  ('valor -> NOMBRE','valor',1,'p_valor','implementation_nico.py',53),
  ('valor -> booleano','valor',1,'p_valor','implementation_nico.py',54),
  ('valor -> cadena','valor',1,'p_valor','implementation_nico.py',55),
  ('cadena -> STRING','cadena',1,'p_cadena','implementation_nico.py',59),
  ('cadena -> PAR_IZQ STR STRING STRING PAR_DER','cadena',5,'p_cadena','implementation_nico.py',60),
  ('booleano -> TRUE','booleano',1,'p_booleano','implementation_nico.py',64),
  ('booleano -> FALSE','booleano',1,'p_booleano','implementation_nico.py',65),
  ('numero -> ENTERO','numero',1,'p_numero','implementation_nico.py',69),
  ('numero -> FLOTANTE','numero',1,'p_numero','implementation_nico.py',70),
]
