reservadas={
    "def": "VARIABLE",
    "nil": "NULL",
    "hash-map": "HASHMAP",
    "sorted-map": "SORTEDMAP",
    "vector": "VECTOR",
    "set": "CONJUNTO",
    "str": "STR",
    'loop':'LOOP',
    'do':'DO',
    'when':'WHEN',
    'println':'PRINTLN',
    'recur': 'RECUR',
    'defn': 'FUNCION',
    'first': 'METODOFIRST',
    "list": "LISTA",
    "nth" : "METODONTH",
    "doseq": "DOSEQ", 
    "true": "TRUE",
    "false": "FALSE"
}

tokens = [
    "ENTERO",
    "FLOTANTE",
    "CHAR",
    "STRING",
    "PAR_DER",
    "PAR_IZQ",
    "COR_DER",
    "COR_IZQ",
    "SUMA",
    "RESTA",
    "PRODUCTO",
    "DIVISION",
    "POTENCIA",
    'AND',
    "OR",
    "NOT",
    'EQUAL_OP',
    "EQUAL",
    "EQUAL_2",
    "NOT_EQUAL",
    "MAYOR_QUE",
    "MENOR_QUE",
    "ARGS",
    "NOMBRE"
]+ list(reservadas.values())